# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: ""
title: Adam Tait
author: Adam Tait
description: Personal blog and resume
avatar: profile.png
email: yourname@email.com
github: phyr0n
twitter: AdamTaiit
linkedin: AdamTaiit
google_analytics: UA-69391421-1

# site customisation
accent-color: #CC0000

# needed for travis-ci build
exclude: [vendor]
